services:
  - type: web
    name: express-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js   # or your entry point like server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: hwrkjbjvflkfvnlknlk
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: serviceAccountKey.json  # optional if handled in code
    autoDeploy: true
    branch: main
    repo: https://github.com/vedant2709/server-deployment
    region: oregon
